### PR TITLE
Transfer

### PR DESCRIPTION
**Pull request by baharudindayat**
fix transaksi entity and endpoint url

### CODE REVIEW

**Review by Devanoz — APPROVED** [review]
so far oke

**Comment by hambuddy** [comment]
pade oke aku oke

**Review by Devanoz — APPROVED** [review]
dah oke

**Review by hambuddy — APPROVED** [review]
okoc

**Review by fahrizalvianaz — APPROVED** [review]
appr

**Review by alamsyhhh — APPROVED** [review]
approve

**Pull request merged**
